### ISSUE TITLE
Compiling AMP code crashes July's closure compiler 

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp-closure-compiler#22]
Here are the errors:
```
[13:59:49] ERROR: Could not minify v0.js
src/amp.js:158: 
Originally at:
src/amp.js:158: WARNING - [JSC_UNREACHABLE_CODE] unreachable code
  158|     if (false) {
                       ^
  159|       bootstrap(ampdoc, perf);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  160|     } else {
       ^^^^^^

src/css.js:106: 
Originally at:
src/css.js:106: WARNING - [JSC_UNREACHABLE_CODE] unreachable code
  106|   if (false) {
                     ^
  107|     return CSS.escape(ident);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  108|   }
       ^^^

src/custom-element.js:226: 
Originally at:
src/custom-element.js:226: WARNING - [JSC_SUSPICIOUS_LEFT_OPERAND_OF_LOGICAL_OPERATOR] Left operand of && operator is always falsy.
  226|       if (false && nonStructThis['implementationClassForTesting']) {
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

java.lang.StringIndexOutOfBoundsException: String index out of range: 75
        at java.lang.StringLatin1.charAt(StringLatin1.java:47)
        at java.lang.String.charAt(String.java:693)
        at com.google.javascript.jscomp.LightweightMessageFormatter.padLine(LightweightMessageFormatter.java:197)
        at com.google.javascript.jscomp.LightweightMessageFormatter.padMultipleLines(LightweightMessageFormatter.java:251)
        at com.google.javascript.jscomp.LightweightMessageFormatter.getExcerptWithPosition(LightweightMessageFormatter.java:161)
        at com.google.javascript.jscomp.LightweightMessageFormatter.format(LightweightMessageFormatter.java:133)
        at com.google.javascript.jscomp.LightweightMessageFormatter.formatWarning(LightweightMessageFormatter.java:86)
        at com.google.javascript.jscomp.JSError.format(JSError.java:171)
        at com.google.javascript.jscomp.PrintStreamErrorReportGenerator.println(PrintStreamErrorReportGenerator.java:56)
        at com.google.javascript.jscomp.PrintStreamErrorReportGenerator.generateReport(PrintStreamErrorReportGenerator.java:50)
        at com.google.javascript.jscomp.SortingErrorManager.generateReport(SortingErrorManager.java:116)
        at com.google.javascript.jscomp.ThreadSafeDelegatingErrorManager.generateReport(ThreadSafeDelegatingErrorManager.java:40)
        at com.google.javascript.jscomp.Compiler.generateReport(Compiler.java:724)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.performFullCompilation(AbstractCommandLineRunner.java:1336)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1254)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:540)
        at org.ampproject.AmpCommandLineRunner.main(Unknown Source)

[13:59:49] 'dist' errored after 26 s
[13:59:49] Error in plugin 'gulp-google-closure-compiler'
Compilation errors occurred
```

**Comment by kristoferbaxter** [comment]
Looks like this is blocking an issue now: https://github.com/ampproject/amphtml/pull/30043

**Comment by rsimha** [comment]
Let me try September's compiler released [3 days ago](https://github.com/google/closure-compiler/releases). If I manage to get it working, I'll enable automatic updates for the closure dependency so each new release is tested. Coming up.

**Comment by rsimha** [comment]
@jridgewell, is it expected that cl/329596241 will have fixed this bug? If not, any idea where the `StringIndexOutOfBoundsException` is coming from?

**Comment by jridgewell** [comment]
> is it expected that cl/329596241 will have fixed this bug? 

No, that fixes an unrelated bug with code printing (closure's output was invalid JS). I have no idea why closure is throwing an exception.

**Comment by rsimha** [comment]
@kristoferbaxter Based on the fact that the crash started happening after May, I suspect the cause lies in the `google/closure-compiler:src/com/google/javascript/jscomp/LightweightMessageFormatter.java:padLine()` implementation change that was made in this commit: https://github.com/google/closure-compiler/commit/9b7ad9285531be6e3ebfd28c0110920ac688c6c2#diff-9ec5d601e3bec169fb92f4f40d972837R191

I'm still unclear about which of AMP's error messages is causing closure to crash.

**Comment by rsimha** [comment]
After more debugging, I managed to track down the line in `amphtml` that's resulting in a closure warning, which in turn is crashing closure during formatting.

Here is the original source code [line](https://github.com/ampproject/amphtml/blob/593424aa171ae06c901ef81f86b8eab55c3a8a51/src/custom-element.js#L226) in `amphtml`:

```js
      if (getMode().test && nonStructThis['implementationClassForTesting']) {
```

The length of this line is 77 chars. However, when variable substitution converts `getMode().test` to `false`, the code effectively becomes:

```js
      if (false && nonStructThis['implementationClassForTesting']) {
```

The length of this modified line is 68 chars, and it results in closure reporting a warning for the seemingly unnecessary `false` in the `if` block.

When the `padLine()` function is [being called](https://github.com/google/closure-compiler/blob/a95d9b52d7e9aa3975ead28070d4af5bc5d39d15/src/com/google/javascript/jscomp/LightweightMessageFormatter.java#L252) from `LightweightMessageFormatter.java:padMultipleLines()` to format this warning, it is being passed an offset value (`charWithLineNumberOffset`) of 75, which is out of bounds for the modified 68 character-long line.

```js
        padLine(charWithLineNumberOffset, line, b, remainingLength, errorNode);
```

Thus, the call stack in the crash:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 75
        at java.lang.StringLatin1.charAt(StringLatin1.java:47)
        at java.lang.String.charAt(String.java:693)
        at com.google.javascript.jscomp.LightweightMessageFormatter.padLine(LightweightMessageFormatter.java:197)
        at com.google.javascript.jscomp.LightweightMessageFormatter.padMultipleLines(LightweightMessageFormatter.java:251)
        at com.google.javascript.jscomp.LightweightMessageFormatter.getExcerptWithPosition(LightweightMessageFormatter.java:161)
        at com.google.javascript.jscomp.LightweightMessageFormatter.format(LightweightMessageFormatter.java:133)
        at com.google.javascript.jscomp.LightweightMessageFormatter.formatWarning(LightweightMessageFormatter.java:86)
        at com.google.javascript.jscomp.JSError.format(JSError.java:171)
        at com.google.javascript.jscomp.PrintStreamErrorReportGenerator.println(PrintStreamErrorReportGenerator.java:56)
        at com.google.javascript.jscomp.PrintStreamErrorReportGenerator.generateReport(PrintStreamErrorReportGenerator.java:50)
        at com.google.javascript.jscomp.SortingErrorManager.generateReport(SortingErrorManager.java:116)
        at com.google.javascript.jscomp.ThreadSafeDelegatingErrorManager.generateReport(ThreadSafeDelegatingErrorManager.java:40)
        at com.google.javascript.jscomp.Compiler.generateReport(Compiler.java:724)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.performFullCompilation(AbstractCommandLineRunner.java:1336)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1254)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:540)
        at org.ampproject.AmpCommandLineRunner.main(Unknown Source)

```

The last question (to which I don't know the answer) is: Why is `padMultipleLines()` computing an incorrect offset, and how can we fix it? (I'm pretty sure the bug came in as part of https://github.com/google/closure-compiler/commit/9b7ad9285531be6e3ebfd28c0110920ac688c6c2#diff-9ec5d601e3bec169fb92f4f40d972837R191, but haven't been able to spot it yet.)

@kristoferbaxter @jridgewell Do you think my theory holds water? Any insights you can help provide?

**Comment by kristoferbaxter** [comment]
A smaller distilled example of just this line with replacement could be useful for the Closure Compiler team.

Besides this, I would see if we can compile the `getMode().test` => `false` in babel before handing the code to Closure Compiler.

**Comment by rsimha** [comment]
> Besides this, I would see if we can compile the `getMode().test` => `false` in babel before handing the code to Closure Compiler.

We already transform `getMode.test()` to `false` via `build-system/babel-plugins/babel-plugin-amp-mode-transformer/index.js`.

**Comment by jridgewell** [comment]
It might be sourcemap related?

**Comment by dvoytenko** [comment]
Any update here? We do have a number of problems with an older Preact that I'd really like to upgrade soon and this issue appears to block it.

**Comment by jridgewell** [comment]
I think the issue here is that our source file name and our transformed (post-babel pre-closure) filename match. Closure will look at the error it's generating, find the original source line/column, then try to print the error. When it does this, it tries to look up the source code, too, but since the names match, it finds our transformed file instead! The line in our transformed file isn't as long as the original one, so as we try to print the error (using line/column from the original), we hit out OOB.

**Comment by rsimha** [comment]
This issue has been mitigated for AMP development by #29, https://github.com/ampproject/amphtml/pull/30987, and https://github.com/ampproject/amphtml/pull/31072. The underlying cause will be fixed in closure code via https://github.com/google/closure-compiler/issues/3720. Meanwhile, this issue can be closed.

Thanks to @jridgewell and @kristoferbaxter for the help!
